# SPDX-License-Identifier: PMPL-1.0-or-later
homepage: "https://github.com/hyperpolymath/idaptik"
language: rust
primary_contact: "j.d.a.jewell@open.ac.uk"
main_repo: "https://github.com/hyperpolymath/idaptik.git"
